// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YMS.Infrastructure.Data;

#nullable disable

namespace YMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(YmsDbContext))]
    [Migration("20260531161750_AddVehicleLegalHold")]
    partial class AddVehicleLegalHold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YMS.Domain.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuctionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BuyerContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("HighestBid")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReservePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("YMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "HDFC Manager",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5736),
                            Email = "hdfc@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HDFC Bank",
                            Phone = "9000000001"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "ICICI Manager",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5747),
                            Email = "icici@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ICICI Bank",
                            Phone = "9000000002"
                        },
                        new
                        {
                            Id = 3,
                            ContactPerson = "Axis Manager",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5749),
                            Email = "axis@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Axis Bank",
                            Phone = "9000000003"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValuationAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValuationAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("YMS.Domain.Entities.MasterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name")
                        .IsUnique();

                    b.ToTable("MasterItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5979),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Andhra Pradesh",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5993),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Arunachal Pradesh",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6001),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Assam",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6003),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bihar",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6005),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chhattisgarh",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6015),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Goa",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6018),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gujarat",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6019),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Haryana",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6021),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Himachal Pradesh",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6036),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jharkhand",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 11,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6039),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Karnataka",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6040),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kerala",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 13,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6042),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Madhya Pradesh",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 14,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6043),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maharashtra",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 15,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6045),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Manipur",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 16,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6046),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Meghalaya",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 17,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6048),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mizoram",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 18,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6050),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nagaland",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 19,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6051),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Odisha",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 20,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6064),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Punjab",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 21,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6065),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rajasthan",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 22,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6067),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sikkim",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 23,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6071),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tamil Nadu",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 24,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6083),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Telangana",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 25,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6085),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tripura",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 26,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6087),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Uttar Pradesh",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 27,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6088),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Uttarakhand",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 28,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6090),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "West Bengal",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 29,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6091),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Delhi",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = 30,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6105),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jammu and Kashmir",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = 31,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6107),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ladakh",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 32,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6282),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Car",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 33,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6285),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bike",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6288),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Truck",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6290),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bus",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 36,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6291),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 37,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6293),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Van",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 38,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6294),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tractor",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 39,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6296),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SUV",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 40,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6297),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Other",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 41,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6303),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Running",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 42,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6305),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Red/Idle",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 43,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6306),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auctioned",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 44,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6307),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Released",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 45,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6308),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sold",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 46,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6310),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Scrap",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 47,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6316),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yes",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 48,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6318),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "No",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 49,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6320),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Duplicate Key",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 50,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6322),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Missing",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 51,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6326),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Submitted",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 52,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6328),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 53,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6329),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Not Available",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 54,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6330),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Duplicate",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 55,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6335),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Petrol",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 56,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6337),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diesel",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 57,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6338),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CNG",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 58,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6340),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 59,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6341),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hybrid",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 60,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6343),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "LPG",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 61,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6347),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Manual",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 62,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6348),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Automatic",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 63,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6350),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CVT",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 64,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6352),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AMT",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 65,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(6353),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "DCT",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("YMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 777, DateTimeKind.Utc).AddTicks(6219),
                            Email = "admin@yms.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$A.8aNhP0MoShZChZ9Ym/vueq/C0JqOY7TRXxrbESk.GDFTgZ4oOD6",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InsuranceAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLegalHold")
                        .HasColumnType("bit");

                    b.Property<string>("KeyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<decimal>("MiscCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdometerReading")
                        .HasColumnType("int");

                    b.Property<decimal>("ParkingCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RcStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunningStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TowingCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyreCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("YardId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "DocumentType");

                    b.ToTable("VehicleDocuments");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleExitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatePassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverIdProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleExitRequests");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromYardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ToYardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromYardId");

                    b.HasIndex("Status");

                    b.HasIndex("ToYardId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleTransfers");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Yard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Yards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Andheri West",
                            Capacity = 0,
                            City = "Mumbai",
                            ContactNumber = "9111111111",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5843),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Ravi Kumar",
                            Name = "Mumbai Yard",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kharadi",
                            Capacity = 0,
                            City = "Pune",
                            ContactNumber = "9222222222",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5846),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Suresh Patil",
                            Name = "Pune Yard",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Malviya Nagar",
                            Capacity = 0,
                            City = "Jaipur",
                            ContactNumber = "9333333333",
                            CreatedAt = new DateTime(2026, 5, 31, 16, 17, 47, 974, DateTimeKind.Utc).AddTicks(5849),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Ramesh Sharma",
                            Name = "Jaipur Yard",
                            State = "Rajasthan"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Auction", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Project", b =>
                {
                    b.HasOne("YMS.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("YMS.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Report", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Reports")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMS.Domain.Entities.Project", "Project")
                        .WithMany("Vehicles")
                        .HasForeignKey("ProjectId");

                    b.HasOne("YMS.Domain.Entities.Yard", "Yard")
                        .WithMany("Vehicles")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Project");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleExitRequest", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.VehicleTransfer", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Yard", "FromYard")
                        .WithMany()
                        .HasForeignKey("FromYardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMS.Domain.Entities.Yard", "ToYard")
                        .WithMany()
                        .HasForeignKey("ToYardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromYard");

                    b.Navigation("ToYard");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Client", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Project", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Yard", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
