// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YMS.Infrastructure.Data;

#nullable disable

namespace YMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(YmsDbContext))]
    [Migration("20260530090533_AddMasterItems")]
    partial class AddMasterItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "HDFC Manager",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(759),
                            Email = "hdfc@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HDFC Bank",
                            Phone = "9000000001"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "ICICI Manager",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(766),
                            Email = "icici@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ICICI Bank",
                            Phone = "9000000002"
                        },
                        new
                        {
                            Id = 3,
                            ContactPerson = "Axis Manager",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(770),
                            Email = "axis@yms.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Axis Bank",
                            Phone = "9000000003"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.MasterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name")
                        .IsUnique();

                    b.ToTable("MasterItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(984),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Andhra Pradesh",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(992),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Arunachal Pradesh",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(997),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Assam",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1001),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bihar",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1004),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chhattisgarh",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1017),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Goa",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1021),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gujarat",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1023),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Haryana",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1027),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Himachal Pradesh",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1031),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jharkhand",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 11,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1035),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Karnataka",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1037),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kerala",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 13,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1040),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Madhya Pradesh",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 14,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1042),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maharashtra",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 15,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1045),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Manipur",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 16,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1048),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Meghalaya",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 17,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1051),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mizoram",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 18,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1055),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nagaland",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 19,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1058),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Odisha",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 20,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1061),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Punjab",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 21,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1064),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rajasthan",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 22,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1067),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sikkim",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 23,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1069),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tamil Nadu",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 24,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1082),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Telangana",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 25,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1085),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tripura",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 26,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1088),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Uttar Pradesh",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 27,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1091),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Uttarakhand",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 28,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1094),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "West Bengal",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 29,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1097),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Delhi",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = 30,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1120),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jammu and Kashmir",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = 31,
                            Category = "State",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1124),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ladakh",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 32,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1150),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Car",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 33,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1154),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bike",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1158),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Truck",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1161),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bus",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 36,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1164),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auto",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 37,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1167),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Van",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 38,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1169),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tractor",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 39,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1172),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SUV",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 40,
                            Category = "VehicleType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1175),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Other",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 41,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1186),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Running",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 42,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1189),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Red/Idle",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 43,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1192),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Auctioned",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 44,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1195),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Released",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 45,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1198),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sold",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 46,
                            Category = "RunningStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1201),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Scrap",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 47,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1210),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yes",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 48,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1213),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "No",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 49,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1217),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Duplicate Key",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 50,
                            Category = "KeyStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1220),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Missing",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 51,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1229),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Submitted",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 52,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1232),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 53,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1235),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Not Available",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 54,
                            Category = "RcStatus",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1239),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Duplicate",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 55,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1247),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Petrol",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 56,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1250),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diesel",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 57,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1253),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CNG",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 58,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1256),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 59,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1368),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hybrid",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 60,
                            Category = "FuelType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1372),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "LPG",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 61,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1381),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Manual",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 62,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1385),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Automatic",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 63,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1388),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CVT",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 64,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1392),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AMT",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 65,
                            Category = "TransmissionType",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(1395),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "DCT",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("YMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 31, 937, DateTimeKind.Utc).AddTicks(7200),
                            Email = "admin@yms.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$zvEquDJvS.IqjMqq8H4p5uwJ/uXrPQW50l6YJWt9XcxXqKDvcY5lm",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InsuranceAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<decimal>("MiscCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdometerReading")
                        .HasColumnType("int");

                    b.Property<decimal>("ParkingCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RcStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunningStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TowingCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyreCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("YardId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Yard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Yards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Andheri West",
                            City = "Mumbai",
                            ContactNumber = "9111111111",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(887),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Ravi Kumar",
                            Name = "Mumbai Yard",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kharadi",
                            City = "Pune",
                            ContactNumber = "9222222222",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(894),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Suresh Patil",
                            Name = "Pune Yard",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Malviya Nagar",
                            City = "Jaipur",
                            ContactNumber = "9333333333",
                            CreatedAt = new DateTime(2026, 5, 30, 9, 5, 32, 204, DateTimeKind.Utc).AddTicks(898),
                            IsActive = true,
                            IsDeleted = false,
                            ManagerName = "Ramesh Sharma",
                            Name = "Jaipur Yard",
                            State = "Rajasthan"
                        });
                });

            modelBuilder.Entity("YMS.Domain.Entities.Report", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Reports")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("YMS.Domain.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMS.Domain.Entities.Yard", "Yard")
                        .WithMany("Vehicles")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Client", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("YMS.Domain.Entities.Yard", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
